import React from 'react';
import ReactMarkdown from 'react-markdown';

const ReportModal = ({ isOpen, onClose, reportData }) => {
  if (!isOpen || !reportData) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[9999] bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
      {/* Print Styles */}
      <style>
        {`
          @media print {
            body * { visibility: hidden; }
            #print-area, #print-area * { visibility: visible; }
            #print-area { position: absolute; left: 0; top: 0; width: 100%; color: black !important; background: white !important; }
            .no-print { display: none !important; }
          }
        `}
      </style>
      
      <div className="bg-slate-900 border border-slate-700 w-full max-w-4xl max-h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-700 flex items-center justify-between bg-slate-800 no-print shrink-0">
          <div>
            <h2 className="text-xl font-bold text-white">AI Generated Report</h2>
            <p className="text-sm text-slate-400">Period: {reportData.period}</p>
          </div>
          <div className="flex gap-3">
            <button onClick={handlePrint} className="px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg text-sm font-bold shadow transition-colors flex items-center gap-2">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
              Print / Save PDF
            </button>
            <button onClick={onClose} className="p-2 text-slate-400 hover:text-white transition-colors">
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
          </div>
        </div>

        {/* Content */}
        <div id="print-area" className="flex-1 overflow-y-auto p-8 bg-white text-slate-900 custom-scrollbar">
          <div className="max-w-3xl mx-auto">
            <div className="border-b-2 border-slate-800 pb-4 mb-6">
              <h1 className="text-3xl font-black text-slate-900 uppercase tracking-wide">Traffic Management Report</h1>
              <p className="text-slate-600 font-semibold mt-2">Generated by AI Analytics System on {new Date(reportData.generated_at).toLocaleString()}</p>
              <p className="text-slate-600">Reporting Period: {reportData.period}</p>
            </div>
            
            <div className="prose prose-slate max-w-none prose-headings:text-slate-900 prose-h2:border-b prose-h2:pb-2 prose-h2:border-slate-200">
              <ReactMarkdown>{reportData.report_text}</ReactMarkdown>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportModal;
